### ISSUE TITLE
Opening a device kills the app

### ISSUE THREAD

**Issue by katerasrael** [developerfromjokela/motioneye-client#17]
OnePlus Nord, Android 10

Added successfully a device via the wizard, see it in the main screen. Opening the device kills the app immediately

**Comment by developerfromjokela** [comment]
Hello!
Are you able to get any logs?

**Comment by katerasrael** [comment]
Hey, how do i get the logs? It's an unrooted device. Are there any app logs i can activate?

**Comment by katerasrael** [comment]
Ok, i managed to get a logfile:

Process: com.developerfromjokela.motioneyeclient
PID: 14778
UID: 10293
Flags: 0x38c8be44
Package: com.developerfromjokela.motioneyeclient v10000197 (1.0.1)
Foreground: Yes
Build: OnePlus/Nord_EEA/Nord:10/QKQ1.200412.002/2009260426:user/release-keys

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
	at com.developerfromjokela.motioneyeclient.ui.utils.URLUtils.getDomainName(URLUtils.java:51)
	at com.developerfromjokela.motioneyeclient.ui.utils.ConnectionUtils$HostCheckAsync.doInBackground(ConnectionUtils.java:59)
	at com.developerfromjokela.motioneyeclient.ui.utils.ConnectionUtils$HostCheckAsync.doInBackground(ConnectionUtils.java:42)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

**Comment by developerfromjokela** [comment]
Hello!
Nice, you figured it out! 

Thanks for your log file. I'll take a look later today ☺️

**Comment by developerfromjokela** [comment]
@katerasrael Can you send your device's URLs? Including the DDNS one?
