### ISSUE TITLE
Crash on connect

### ISSUE THREAD

**Issue by Bluscream** [developerfromjokela/motioneye-client#24]
[Device info](https://gist.github.com/Bluscream/65c552e112f0c2aa890e869eb5667b38)

<details>
<summary>Screenshot(s)</summary>

![Screenshot_2023-05-19-18-45-30-334](https://github.com/developerfromjokela/motioneye-client/assets/3318223/deb22290-c4cd-4ea0-aac8-0ddaaa008e70)

![Screenshot_2023-05-19-18-45-53-932](https://github.com/developerfromjokela/motioneye-client/assets/3318223/73340292-0374-4189-9dee-2b817c736cd0)

</details>

(App works 100% fine on my redmi note 7 phone btw)

```
build.board: achilles6_row_wifi
build.bootloader: unknown
build.brand: Lenovo
build.cpu_abi: arm64-v8a
build.cpu_abi2: 
build.device: X606F
build.display: TB-X606F_S300554_220303_BMP
build.fingerprint: Lenovo/LenovoTB-X606F_EEA/X606F:10/QP1A.190711.020/TB-X606F_USR_S300554_2203030006_V9.56_BMP_ROW:user/release-keys
build.hardware: mt8768
build.host: bjsl152
build.id: QP1A.190711.020
build.manufacturer: LENOVO
build.model: Lenovo TB-X606F
build.product: LenovoTB-X606F_EEA
build.radio: unknown
build.serial: unknown
build.tags: release-keys
build.time: 1646243318000
build.type: user
build.user: buildslave
version.codename: REL
version.incremental: TB-X606F_USR_S300554_2203030006_V9.56_BMP_ROW
version.release: 10
version.sdk_int: 29
```

**Comment by Bluscream** [comment]
<details>
<summary>Logcat</summary>

```
06-04 12:09:02.910 I/ActivityTaskManager( 1148): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x30010000 cmp=com.developerfromjokela.motioneyeclient/.ui.activities.MainActivity} from uid 10439
06-04 12:09:02.935 D/PowerHalWrapper( 1148): <amsBoostResume> last:io.github.muntashirakon.AppManager, next:com.developerfromjokela.motioneyeclient 
06-04 12:09:02.947 D/PowerHalWrapper( 1148): amsBoostNotify pid:31839,activity:com.developerfromjokela.motioneyeclient.ui.activities.MainActivity, package:com.developerfromjokela.motioneyeclient, mProcessCreatePackcom.developerfromjokela.motioneyeclient 
06-04 12:09:02.948 I/libPowerHal(  459): [perfNotifyAppState] foreground:com.developerfromjokela.motioneyeclient, pid:31839, uid:10189
06-04 12:09:02.949 I/powerd  (  459): [powerd_req] POWER_MSG_NOTIFY_STATE, pc:0, io.github.muntashirakon.AppManager => com.developerfromjokela.motioneyeclient
06-04 12:09:02.999 I/BufferQueueConsumer(  471): [Splash Screen com.developerfromjokela.motioneyeclient#0](this:0x74eda8f000,id:943,api:0,p:-1,c:471) setConsumerName: Splash Screen com.developerfromjokela.motioneyeclient#0
06-04 12:09:02.999 I/BufferQueueConsumer(  471): [Splash Screen com.developerfromjokela.motioneyeclient#0](this:0x74eda8f000,id:943,api:0,p:-1,c:471) setDefaultBufferSize: width=1560 height=1020
06-04 12:09:03.007 I/BufferQueueProducer(  471): [Splash Screen com.developerfromjokela.motioneyeclient#0](this:0x74eda8f000,id:943,api:2,p:1148,c:471) connect(P): api=2 producer=(1148:system_server) producerControlledByApp=false
06-04 12:09:03.010 D/ApplicationPackageManager(31839): hasSystemFeature android.software.picture_in_picture com.developerfromjokela.motioneyeclient
06-04 12:09:03.272 I/WindowManager( 1148): Relayout Window{f8fcc74 u0 com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.MainActivity}: oldVis=4 newVis=0 focusMayChange = true
06-04 12:09:03.278 I/BufferQueueConsumer(  471): [com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.MainActivity#0](this:0x74f94a8800,id:944,api:0,p:-1,c:471) setConsumerName: com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.MainActivity#0
06-04 12:09:03.278 I/BufferQueueConsumer(  471): [com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.MainActivity#0](this:0x74f94a8800,id:944,api:0,p:-1,c:471) setDefaultBufferSize: width=1560 height=1020
06-04 12:09:03.285 I/BufferQueueProducer(  471): [com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.MainActivity#0](this:0x74f94a8800,id:944,api:1,p:31839,c:471) connect(P): api=1 producer=(31839:com.developerfromjokela.motioneyeclient) producerControlledByApp=false
06-04 12:09:03.355 I/BufferQueueProducer(  471): [Splash Screen com.developerfromjokela.motioneyeclient#0](this:0x74eda8f000,id:943,api:2,p:1148,c:471) disconnect(P): api 2
06-04 12:09:03.356 I/ActivityTaskManager( 1148): Displayed com.developerfromjokela.motioneyeclient/.ui.activities.MainActivity: +441ms
06-04 12:09:03.407 I/BufferQueue(  471): [Splash Screen com.developerfromjokela.motioneyeclient#0](this:0x74eda8f000,id:943,api:2,p:-1,c:-1) ~BufferQueueCore
06-04 12:09:04.923 I/ActivityTaskManager( 1148): START u0 {cmp=com.developerfromjokela.motioneyeclient/.ui.activities.CameraViewer (has extras)} from uid 10189
06-04 12:09:04.931 D/PowerHalWrapper( 1148): <amsBoostResume> last:com.developerfromjokela.motioneyeclient, next:com.developerfromjokela.motioneyeclient 
06-04 12:09:04.952 D/PowerHalWrapper( 1148): amsBoostNotify pid:31839,activity:com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer, package:com.developerfromjokela.motioneyeclient, mProcessCreatePackcom.developerfromjokela.motioneyeclient 
06-04 12:09:04.967 D/ApplicationPackageManager(31839): hasSystemFeature android.software.picture_in_picture com.developerfromjokela.motioneyeclient
06-04 12:09:05.131 I/WindowManager( 1148): Relayout Window{f11e6e9 u0 com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer}: oldVis=4 newVis=0 focusMayChange = true
06-04 12:09:05.137 I/BufferQueueConsumer(  471): [com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer#0](this:0x74f950d000,id:945,api:0,p:-1,c:471) setConsumerName: com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer#0
06-04 12:09:05.137 I/BufferQueueConsumer(  471): [com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer#0](this:0x74f950d000,id:945,api:0,p:-1,c:471) setDefaultBufferSize: width=1560 height=1020
06-04 12:09:05.143 I/BufferQueueProducer(  471): [com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer#0](this:0x74f950d000,id:945,api:1,p:31839,c:471) connect(P): api=1 producer=(31839:com.developerfromjokela.motioneyeclient) producerControlledByApp=false
06-04 12:09:05.244 I/BufferQueueProducer(  471): [com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.MainActivity#0](this:0x74f94a8800,id:944,api:1,p:31839,c:471) queueBuffer: fps=1.58 dur=1903.68 max=1852.80 min=20.63
06-04 12:09:05.328 I/BufferQueueProducer(  471): [com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.MainActivity#0](this:0x74f94a8800,id:944,api:1,p:31839,c:471) disconnect(P): api 1
06-04 12:09:05.391 I/BufferQueue(  471): [com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.MainActivity#0](this:0x74f94a8800,id:944,api:1,p:-1,c:-1) ~BufferQueueCore
06-04 12:09:06.461 I/BufferQueueProducer(  471): [com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer#0](this:0x74f950d000,id:945,api:1,p:31839,c:471) queueBuffer: fps=2.43 dur=1234.15 max=1148.81 min=33.46
06-04 12:09:06.491 E/AndroidRuntime(31839): Process: com.developerfromjokela.motioneyeclient, PID: 31839
06-04 12:09:06.491 E/AndroidRuntime(31839): 	at com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer$4.run(CameraViewer.java:326)
06-04 12:09:06.491 E/AndroidRuntime(31839): 	at com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer$2.onRefreshRequest(CameraViewer.java:135)
06-04 12:09:06.491 E/AndroidRuntime(31839): 	at com.developerfromjokela.motioneyeclient.ui.adapters.HttpCamerasAdapter$1.onClick(HttpCamerasAdapter.java:113)
06-04 12:09:06.498 W/ActivityTaskManager( 1148):   Force finishing activity com.developerfromjokela.motioneyeclient/.ui.activities.CameraViewer
06-04 12:09:06.503 D/PowerHalWrapper( 1148): <amsBoostResume> last:com.developerfromjokela.motioneyeclient, next:com.developerfromjokela.motioneyeclient 
06-04 12:09:06.517 I/ActivityManager( 1148): Showing crash dialog for package com.developerfromjokela.motioneyeclient u0
06-04 12:09:06.581 I/BufferQueueConsumer(  471): [Application Error: com.developerfromjokela.motioneyeclient#0](this:0x74f9599000,id:946,api:0,p:-1,c:471) setConsumerName: Application Error: com.developerfromjokela.motioneyeclient#0
06-04 12:09:06.581 I/BufferQueueConsumer(  471): [Application Error: com.developerfromjokela.motioneyeclient#0](this:0x74f9599000,id:946,api:0,p:-1,c:471) setDefaultBufferSize: width=960 height=391
06-04 12:09:06.603 I/BufferQueueProducer(  471): [Application Error: com.developerfromjokela.motioneyeclient#0](this:0x74f9599000,id:946,api:1,p:1148,c:471) connect(P): api=1 producer=(1148:system_server) producerControlledByApp=false
06-04 12:09:07.002 W/ActivityTaskManager( 1148): Activity top resumed state loss timeout for ActivityRecord{ba6f63b u0 com.developerfromjokela.motioneyeclient/.ui.activities.CameraViewer t290 f}
06-04 12:09:07.003 W/ActivityTaskManager( 1148): Activity pause timeout for ActivityRecord{ba6f63b u0 com.developerfromjokela.motioneyeclient/.ui.activities.CameraViewer t290 f}
06-04 12:09:07.006 D/PowerHalWrapper( 1148): amsBoostNotify pid:31839,activity:com.developerfromjokela.motioneyeclient.ui.activities.MainActivity, package:com.developerfromjokela.motioneyeclient, mProcessCreatePackcom.developerfromjokela.motioneyeclient 
06-04 12:09:07.600 W/ActivityTaskManager( 1148):   Force finishing activity com.developerfromjokela.motioneyeclient/.ui.activities.CameraViewer
06-04 12:09:07.601 I/BufferQueueProducer(  471): [Application Error: com.developerfromjokela.motioneyeclient#0](this:0x74f9599000,id:946,api:1,p:1148,c:471) disconnect(P): api 1
06-04 12:09:07.609 W/ActivityTaskManager( 1148):   Force finishing activity com.developerfromjokela.motioneyeclient/.ui.activities.MainActivity
06-04 12:09:07.640 E/InputDispatcher( 1148): Window handle Window{69e7b8a u0 Application Error: com.developerfromjokela.motioneyeclient} has no registered input channel
06-04 12:09:07.656 E/InputDispatcher( 1148): Window handle Window{69e7b8a u0 Application Error: com.developerfromjokela.motioneyeclient} has no registered input channel
06-04 12:09:07.660 I/ActivityManager( 1148): Killing 31839:com.developerfromjokela.motioneyeclient/u0a189 (adj 0): crash
06-04 12:09:07.672 I/BufferQueue(  471): [Application Error: com.developerfromjokela.motioneyeclient#0](this:0x74f9599000,id:946,api:1,p:-1,c:-1) ~BufferQueueCore
06-04 12:09:07.702 I/BufferQueueProducer(  471): [com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer#0](this:0x74f950d000,id:945,api:1,p:31839,c:471) disconnect(P): api 1
06-04 12:09:07.704 I/BufferQueue(  471): [com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer#0](this:0x74f950d000,id:945,api:1,p:-1,c:-1) ~BufferQueueCore
```

</details>

**Comment by Bluscream** [comment]
<details>
<summary>Logcat</summary>

```
---- May 19, 2023 6:39:11 PM ----

05-19 18:35:50.333 24515 24570 E AndroidRuntime: Process: com.developerfromjokela.motioneyeclient, PID: 24515

05-19 18:35:50.333 24515 24570 E AndroidRuntime: 	at com.developerfromjokela.motioneyeclient.ui.utils.URLUtils.getDomainName(URLUtils.java:51)

05-19 18:35:50.333 24515 24570 E AndroidRuntime: 	at com.developerfromjokela.motioneyeclient.ui.utils.ConnectionUtils$HostCheckAsync.doInBackground(ConnectionUtils.java:59)

05-19 18:35:50.333 24515 24570 E AndroidRuntime: 	at com.developerfromjokela.motioneyeclient.ui.utils.ConnectionUtils$HostCheckAsync.doInBackground(ConnectionUtils.java:42)

05-19 18:38:23.211  1145  3995 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.developerfromjokela.motioneyeclient/.ui.activities.MainActivity bnds=[12,536][391,775]} from uid 10262

05-19 18:38:23.315   468   525 I BufferQueueConsumer: [Splash Screen com.developerfromjokela.motioneyeclient#0](this:0x77e10ec000,id:1549,api:0,p:-1,c:468) setConsumerName: Splash Screen com.developerfromjokela.motioneyeclient#0

05-19 18:38:23.315   468   525 I BufferQueueConsumer: [Splash Screen com.developerfromjokela.motioneyeclient#0](this:0x77e10ec000,id:1549,api:0,p:-1,c:468) setDefaultBufferSize: width=1920 height=1200

05-19 18:38:23.324   468  1129 I BufferQueueProducer: [Splash Screen com.developerfromjokela.motioneyeclient#0](this:0x77e10ec000,id:1549,api:2,p:1145,c:468) connect(P): api=2 producer=(1145:system_server) producerControlledByApp=false

05-19 18:38:23.347  1145  1301 I ActivityManager: Start proc 25188:com.developerfromjokela.motioneyeclient/u0a414 for activity {com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.MainActivity}

05-19 18:38:23.348  5072  5202 I LegacyProcessMonitor: process started (logcat): pid=25188, uid=10414, user=0, proc=com.developerfromjokela.motioneyeclient, package=com.developerfromjokela.motioneyeclient, type=activity

05-19 18:38:23.455   459   489 I libPowerHal: [perfNotifyAppState] foreground:com.developerfromjokela.motioneyeclient, pid:25188, uid:10414

05-19 18:38:23.456   459   489 I powerd  : [powerd_req] POWER_MSG_NOTIFY_STATE, pc:1, com.teslacoilsw.launcher => com.developerfromjokela.motioneyeclient

05-19 18:38:23.526 25188 25188 I chatty  : uid=10414(com.developerfromjokela.motioneyeclient) identical 1 line

05-19 18:38:23.554 25188 25188 I chatty  : uid=10414(com.developerfromjokela.motioneyeclient) identical 1 line

05-19 18:38:23.888  1145  1602 I WindowManager: Relayout Window{c7b4d98 u0 com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.MainActivity}: oldVis=4 newVis=0 focusMayChange = true

05-19 18:38:23.892   468   525 I BufferQueueConsumer: [com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.MainActivity#0](this:0x77e10ed800,id:1550,api:0,p:-1,c:468) setConsumerName: com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.MainActivity#0

05-19 18:38:23.892   468   525 I BufferQueueConsumer: [com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.MainActivity#0](this:0x77e10ed800,id:1550,api:0,p:-1,c:468) setDefaultBufferSize: width=1920 height=1200

05-19 18:38:23.931   468  1129 I BufferQueueProducer: [com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.MainActivity#0](this:0x77e10ed800,id:1550,api:1,p:25188,c:468) connect(P): api=1 producer=(25188:com.developerfromjokela.motioneyeclient) producerControlledByApp=false

05-19 18:38:23.994   468   525 I BufferQueueProducer: [Splash Screen com.developerfromjokela.motioneyeclient#0](this:0x77e10ec000,id:1549,api:2,p:1145,c:468) disconnect(P): api 2

05-19 18:38:24.001  1145  1299 I ActivityTaskManager: Displayed com.developerfromjokela.motioneyeclient/.ui.activities.MainActivity: +782ms

05-19 18:38:24.030   468   468 I BufferQueue: [Splash Screen com.developerfromjokela.motioneyeclient#0](this:0x77e10ec000,id:1549,api:2,p:-1,c:-1) ~BufferQueueCore

05-19 18:38:25.139  1145 13394 I ActivityTaskManager: START u0 {cmp=com.developerfromjokela.motioneyeclient/.ui.activities.CameraViewer (has extras)} from uid 10414

05-19 18:38:25.319  1145  1602 I WindowManager: Relayout Window{5740855 u0 com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer}: oldVis=4 newVis=0 focusMayChange = true

05-19 18:38:25.322   468   526 I BufferQueueConsumer: [com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer#0](this:0x77d561f000,id:1551,api:0,p:-1,c:468) setConsumerName: com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer#0

05-19 18:38:25.322   468   526 I BufferQueueConsumer: [com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer#0](this:0x77d561f000,id:1551,api:0,p:-1,c:468) setDefaultBufferSize: width=1920 height=1200

05-19 18:38:25.327   468   525 I BufferQueueProducer: [com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer#0](this:0x77d561f000,id:1551,api:1,p:25188,c:468) connect(P): api=1 producer=(25188:com.developerfromjokela.motioneyeclient) producerControlledByApp=false

05-19 18:38:25.391   468   526 I BufferQueueProducer: [com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.MainActivity#0](this:0x77e10ed800,id:1550,api:1,p:25188,c:468) queueBuffer: fps=2.13 dur=1408.19 max=1347.85 min=16.80

05-19 18:38:25.454   468   525 I BufferQueueProducer: [com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.MainActivity#0](this:0x77e10ed800,id:1550,api:1,p:25188,c:468) disconnect(P): api 1

05-19 18:38:25.517   468   468 I BufferQueue: [com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.MainActivity#0](this:0x77e10ed800,id:1550,api:1,p:-1,c:-1) ~BufferQueueCore

05-19 18:38:26.288 25188 25188 E AndroidRuntime: Process: com.developerfromjokela.motioneyeclient, PID: 25188

05-19 18:38:26.288 25188 25188 E AndroidRuntime: 	at com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer$4.run(CameraViewer.java:326)

05-19 18:38:26.288 25188 25188 E AndroidRuntime: 	at com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer$2.onRefreshRequest(CameraViewer.java:135)

05-19 18:38:26.288 25188 25188 E AndroidRuntime: 	at com.developerfromjokela.motioneyeclient.ui.adapters.HttpCamerasAdapter$1.onClick(HttpCamerasAdapter.java:113)

05-19 18:38:26.291  1145  1602 W ActivityTaskManager:   Force finishing activity com.developerfromjokela.motioneyeclient/.ui.activities.CameraViewer

05-19 18:38:26.302  1145  1289 I ActivityManager: Showing crash dialog for package com.developerfromjokela.motioneyeclient u0

05-19 18:38:26.351   468   525 I BufferQueueConsumer: [Application Error: com.developerfromjokela.motioneyeclient#0](this:0x77e1195000,id:1552,api:0,p:-1,c:468) setConsumerName: Application Error: com.developerfromjokela.motioneyeclient#0

05-19 18:38:26.351   468   525 I BufferQueueConsumer: [Application Error: com.developerfromjokela.motioneyeclient#0](this:0x77e1195000,id:1552,api:0,p:-1,c:468) setDefaultBufferSize: width=960 height=391

05-19 18:38:26.367   468  2682 I BufferQueueProducer: [Application Error: com.developerfromjokela.motioneyeclient#0](this:0x77e1195000,id:1552,api:1,p:1145,c:468) connect(P): api=1 producer=(1145:system_server) producerControlledByApp=false

05-19 18:38:26.600  1145  1602 W ActivityTaskManager:   Force finishing activity com.developerfromjokela.motioneyeclient/.ui.activities.CameraViewer

05-19 18:38:26.602   468   525 I BufferQueueProducer: [Application Error: com.developerfromjokela.motioneyeclient#0](this:0x77e1195000,id:1552,api:1,p:1145,c:468) disconnect(P): api 1

05-19 18:38:26.613  1145  1602 W ActivityTaskManager:   Force finishing activity com.developerfromjokela.motioneyeclient/.ui.activities.MainActivity

05-19 18:38:26.623   459   489 I powerd  : [powerd_req] POWER_MSG_NOTIFY_STATE, pc:0, com.developerfromjokela.motioneyeclient => com.teslacoilsw.launcher

05-19 18:38:26.642  1145 13394 E InputDispatcher: Window handle Window{2ca345d u0 Application Error: com.developerfromjokela.motioneyeclient} has no registered input channel

05-19 18:38:26.648  1145  1602 I ActivityManager: Killing 25188:com.developerfromjokela.motioneyeclient/u0a414 (adj 0): crash

05-19 18:38:26.659   468   468 I BufferQueue: [Application Error: com.developerfromjokela.motioneyeclient#0](this:0x77e1195000,id:1552,api:1,p:-1,c:-1) ~BufferQueueCore

05-19 18:38:26.684  1145  1679 W InputDispatcher: channel '5740855 com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer (server)' ~ Consumer closed input channel or an error occurred.  events=0x9

05-19 18:38:26.684  1145  1679 E InputDispatcher: channel '5740855 com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer (server)' ~ Channel is unrecoverably broken and will be disposed!

05-19 18:38:26.684  1145  1679 W InputDispatcher: channel 'c7b4d98 com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9

05-19 18:38:26.684  1145  1679 E InputDispatcher: channel 'c7b4d98 com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

05-19 18:38:26.684   468   806 I BufferQueueProducer: [com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer#0](this:0x77d561f000,id:1551,api:1,p:25188,c:468) disconnect(P): api 1

05-19 18:38:26.685  1145  1602 I WindowManager: WIN DEATH: Window{5740855 u0 com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer}

05-19 18:38:26.685  1145  1602 W InputDispatcher: Attempted to unregister already unregistered input channel '5740855 com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer (server)'

05-19 18:38:26.690  1145  1236 I WindowManager: WIN DEATH: Window{c7b4d98 u0 com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.MainActivity}

05-19 18:38:26.690  1145  1236 W InputDispatcher: Attempted to unregister already unregistered input channel 'c7b4d98 com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.MainActivity (server)'

05-19 18:38:26.774   468   468 I BufferQueue: [com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer#0](this:0x77d561f000,id:1551,api:1,p:-1,c:-1) ~BufferQueueCore

05-19 18:38:26.794  1145  1291 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{96a6d74 u0 com.developerfromjokela.motioneyeclient/.ui.activities.CameraViewer t-1 f}

---- May 19, 2023 6:39:11 PM ----
```

</details>

https://github.com/developerfromjokela/motioneye-client/blob/master/app/src/main/java/com/developerfromjokela/motioneyeclient/ui/activities/CameraViewer.java#L326 ?

**Comment by developerfromjokela** [comment]
Hi.

Thanks for sending logcat. I'll have a look in upcoming days at this.

- DFJ

**Comment by Bluscream** [comment]
Damn you made a lot of changes in that commit :o what exactly was the fix?

**Comment by Bluscream** [comment]
New logcat after updating:

```
06-05 13:26:18.783 19999 19999 E AndroidRuntime: Process: com.developerfromjokela.motioneyeclient, PID: 19999

06-05 13:26:18.783 19999 19999 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.developerfromjokela.motioneyeclient.ui.adapters.HttpCamerasAdapter.notifyDataSetChanged()' on a null object reference

06-05 13:26:18.783 19999 19999 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.developerfromjokela.motioneyeclient.ui.adapters.HttpCamerasAdapter.notifyDataSetChanged()' on a null object reference

06-05 13:26:18.783 19999 19999 E AndroidRuntime: 	at com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer.onResume(CameraViewer.java:168)

06-05 13:26:35.433 20170 20170 E AndroidRuntime: Process: com.developerfromjokela.motioneyeclient, PID: 20170

06-05 13:26:35.433 20170 20170 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.developerfromjokela.motioneyeclient.ui.adapters.HttpCamerasAdapter.notifyDataSetChanged()' on a null object reference

06-05 13:26:35.433 20170 20170 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.developerfromjokela.motioneyeclient.ui.adapters.HttpCamerasAdapter.notifyDataSetChanged()' on a null object reference

06-05 13:26:35.433 20170 20170 E AndroidRuntime: 	at com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer.onResume(CameraViewer.java:168)
```

**Comment by Bluscream** [comment]
```
06-05 13:47:50.932 E/AndroidRuntime(30213): Process: com.developerfromjokela.motioneyeclient, PID: 30213
06-05 13:47:50.932 E/AndroidRuntime(30213): java.lang.RuntimeException: Unable to resume activity {com.developerfromjokela.motioneyeclient/com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.developerfromjokela.motioneyeclient.ui.adapters.HttpCamerasAdapter.notifyDataSetChanged()' on a null object reference
06-05 13:47:50.932 E/AndroidRuntime(30213): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.developerfromjokela.motioneyeclient.ui.adapters.HttpCamerasAdapter.notifyDataSetChanged()' on a null object reference
06-05 13:47:50.932 E/AndroidRuntime(30213): 	at com.developerfromjokela.motioneyeclient.ui.activities.CameraViewer.onResume(CameraViewer.java:168)
```
